#
# Copyright 2018-2019 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

language: python

python:
  - 3.6

services:
  - docker

install:
  - docker build -t max-image-caption-generator .
  - docker run -it --rm -d -p 5000:5000 max-image-caption-generator
  - pip install -r requirements-test.txt

before_script:
  - flake8 . --max-line-length=127
  - bandit -r .
  - sleep 30

script:
  - pytest tests/test.py

### Temporarily disable downstream tests ###
#jobs:
#  include:
#    - stage: test
#      script:
#        - pytest tests/test.py
#    - stage: trigger downstream
#      jdk: oraclejdk8
#      script: |
#        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
#        if [[ ($TRAVIS_BRANCH == master) &&
#              ($TRAVIS_PULL_REQUEST == false) ]] ; then
#          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
#          sh trigger-travis.sh IBM MAX-Image-Caption-Generator-Web-App $TRAVIS_ACCESS_TOKEN
#        fi
