language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-image-caption-generator .
  - docker run -it -d -p 5000:5000 max-image-caption-generator
before_script:
  - pip install pytest pycurl
script:
  - pytest tests/test.py
