language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-image-caption-generator .
  - docker run -it -d -p 5000:5000 max-image-caption-generator
before_script:
  - pip install pytest pycurl
script:
  - pytest tests/test.py
jobs:
  include:
    - stage: trigger downstream
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
        sh trigger-travis.sh IBM MAX-Image-Caption-Generator-Web-App $TRAVIS_ACCESS_TOKEN
